In [12]:
import matplotlib.pyplot as plt 
import numpy as np
import time

# Programa 1

Implementa un programa secuencial que calcule el producto de dos matrices (considerablemente grandes,
sugerencia 10, 000 × 10, 000). 

Posteriormente refactoriza el código de tal forma que utilices concurrencia,
por medio de hilos, para que realicen esta tarea de manera conjunta, cada hilo calculará un subconjunto
del producto. Modifica la versión concurrente para hacer un análisis de rendimiento: speed-up y
eficiencia, incluye el procedimiento que elabores para el cómputo de los tiempos y métricas, así como las gráficas correspondientes; no olvides variar el tamaño de las matrices y el número de hilos.

In [3]:
A = np.random.randint(0, 30, size=(3,3))
B = np.random.randint(0,30, size= (3,2))

In [7]:
print('Matriz A:\n',A)

print('Matriz B:\n',B)

Matriz A:
 [[11 22  2]
 [19 10 26]
 [13  1 17]]
Matriz B:
 [[21  2]
 [ 7 28]
 [ 0 17]]


#### Version secuencial

In [ ]:
def multiplicacion_matricial_secuencial(A, B):
    filas_b =len(B)
    columnas_a= len(A[0])
    #Comprobamos que eñl producto este bien definido
    if columnas_a != filas_b:
        return None
    #Creamos una matriz de ceros del número de renglones de A y del número de columnas de B
    new_m = np.zeros((A.shape[0], B.shape[1]))
    
    #Llenamos la matriz 
    for i in range(A.shape[0]): #Filas de A
        for j in range(B.shape[1]): #Columnas de B
            suma = 0
            for k in range(B.shape[0]):  #Filas de B
                suma += A[i][k] * B[k][j]
            new_m[i][j] = suma
    return new_m    

In [ ]:
multiplicacion_matricial_secuencial(A, B)

array([[138., 570.],
       [303., 460.],
       [339., 558.]])

#### Version concurrente

In [ ]:
print('asdf')

In [56]:
import threading as th

new_matriz = []

def multiplicacion_matricial_hilos(A, B):
    global new_matriz    
    #filas_b =len(B)
    #columnas_a= len(A[0])
    #Comprobamos que eñl producto este bien definido
    #if columnas_a != filas_b:
        #print('afs')
        #return None
    #Creamos una matriz de ceros del número de renglones de A y del número de columnas de B
    new_m = np.zeros((A.shape[0], B.shape[1]))
    print(new_m)
   
    print(A)
    print('A.shapehape', A.shape[0], A)
    print(B)
    print('B.shape', B.shape)
    #Llenamos la matriz 
    for i in range(1): #Filas de A
        for j in range(B.shape[1]): #Columnas de B
            suma = 0
            for k in range(B.shape[0]):  #Filas de B
                #print('suma', suma)
                suma += A[i][k] * B[k][j]
                #print('A[i][k]', A[i][k])
            new_m[i][j] = suma
    
    print(new_matriz)
    new_matriz.append(new_m.copy())

hilo = th.Thread(target=multiplicacion_matricial_hilos, args=(A[0,:]., B))
hilo.start()
hilo.join()
print('new_matriz', new_matriz)

SyntaxError: invalid syntax (<ipython-input-56-2d3c8b1013c7>, line 34)

In [ ]:
num_hilos = A.shape[0]

lista_hilos = []

for i in range(num_hilos):
    lista_hilos.append(th.Thread(target=multiplicacion_matricial_secuencial, args=(A [i,:],B)))

# Arrancar hilos
for hilo in lista_hilos:
        hilo.start()

# Esperar hilos
for hilo in lista_hilos:
    hilo.join()

print('new_matriz', new_matriz)

In [ ]:
num_hilos = [i*2 for i in range(1, 9)]
lista_tiempos = []

print(num_hilos)
for hilos in num_hilos:
    lista_hilos = []
    
    # Le asignamos tareas depositar o retirar
    for hilo in range(1,hilos+1):
        lista_hilos.append(th.Thread(target=tareas[hilo%2], args=()))
    
    t = time.time()
    # Arrancar hilos 
    for hilo in lista_hilos:
        hilo.start()
    # Esperar hilos
    for hilo in lista_hilos:
        hilo.join()
    lista_tiempos.append(time.time()-t)
    
print(num_hilos)
print(lista_tiempos)

# Programa 2

Implementa una simulación de la fábula que cuenta la carrera entre la liebre y la tortuga. Para hacerlo
más interesante la carrera será cuesta arriba por una pista resbaladiza, de modo que a veces podrán
resbalar y retroceder algunas posiciones. Habrá un thread (instanciado con clases) que implementará la
tortuga y otro la liebre.

In [34]:
num_hilos

3

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a3e9b61b-ba9a-418b-87d5-cc9bc636f8e1' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>